In [1]:
import numpy as np

def main():
    print("정보통신공학과 60191896 김수정\n")

    #점수 배열
    Score = np.random.randint(100, size=(10, 4))
    print("10명 학생의 국영수과 점수 리스트입니다.\n", Score, "\n")

    sub_avg(Score) #1-1실행하면서 1-2, 1-3, 1-4 모두 실행 / 1-4 실행 시 1-5도 실행됨.

    
#1-1. 과목평균 구해서 11 X 4 행렬 출력
def sub_avg(ScoreList):
    x = ScoreList #main에서 받은 배열 담아놓기
    
    avg_Score = ScoreList.mean(axis=0)
    avg_Score = np.array(avg_Score, dtype=np.int32)
    avg_Score = np.expand_dims(avg_Score, axis=0)
    ScoreList = np.vstack((ScoreList, avg_Score))

    print("1-1.과목들의 평균입니다(맨 아랫줄).\n", ScoreList, "\n")

    #1-2 실행
    sub_abcd(x)
    #1-3 실행
    avg_sub_score(x)
    #1-4실행
    total_score(ScoreList) #1-1에서 만든 11X4행렬을 원소로 가진 함수실행시키기

    

#1-2. 점수별 ABCD 10 X 4 행렬 출력(if사용X)
def sub_abcd(ScoreList):
    A = np.where(ScoreList >= 90, 'A', ScoreList)
    B = np.where((ScoreList < 90) & (ScoreList >= 80), 'B', ScoreList)
    C = np.where((ScoreList < 80) & (ScoreList >= 70), 'C', ScoreList)
    D = np.where(ScoreList < 70, 'D', ScoreList)

    ScoreList = A
    ScoreList = np.where(ScoreList != 'A', B, ScoreList)
    ScoreList = np.where((ScoreList != 'A') & (ScoreList != 'B'), C, ScoreList)
    ScoreList = np.where((ScoreList != 'A') & (ScoreList != 'B') & (ScoreList != 'C'), D, ScoreList)

    print("1-2.과목 점수별 ABCD 입니다. (10 X 4).\n", ScoreList, "\n")

    

#1-3. 각 과목 점수-각 과목 평균 10 X 4 행렬 출력
def avg_sub_score(ScoreList):
    avg_Score = ScoreList.mean(axis=0)
    avg_Score = np.array(avg_Score, dtype=np.int32)

    subtraction = ScoreList - avg_Score
    
    print("1-3. 점수-평균의 값입니다. (10 X 4)\n", subtraction, "\n")

    

#1-4. 1번 문제에 총합 점수를 넣은 11 X 5 행렬 출력
def total_score(ScoreList):
    total = ScoreList.sum(axis=1)
    total = np.expand_dims(total, axis=1)
    ScoreList = np.hstack((ScoreList, total))

    print("1-4. 학생별 과목총합과 평균의 총합을 추가한 배열입니다. (11 X 5)\n", ScoreList, "\n")

    x = ScoreList #1-4에서 만든 배열 담아놓기
    #1-5실행
    avg_column(x)



#1-5. 4번 문제 마지막 행에 과목별 평균값 11 X 6 행렬 출력
def avg_column(ScoreList):
    #평균값 구하기 전, 점수들만 담은 배열 avg값에 담기
    avg = ScoreList[:, 0:4]
    #avg배열의 국수영과 평균 / 과목별 총합 평균
    avg = avg.mean(axis=1)
    avg = np.array(avg, dtype=np.int32)
    avg = np.expand_dims(avg, axis=1)

    avgList = np.hstack((ScoreList, avg))
    
    print("1-5. 과목 평균값 행을 추가한 배열입니다. (11 X 6)\n", avgList, "\n")

    
main()

정보통신공학과 60191896 김수정

10명 학생의 국영수과 점수 리스트입니다.
 [[65 11 58 36]
 [30 73 10 52]
 [56 95 26 27]
 [13  0 98 99]
 [76 89 60 17]
 [39 60 38  6]
 [59  5 41 56]
 [78 61 82 73]
 [32 38 78 35]
 [40 88 13 20]] 

1-1.과목들의 평균입니다(맨 아랫줄).
 [[65 11 58 36]
 [30 73 10 52]
 [56 95 26 27]
 [13  0 98 99]
 [76 89 60 17]
 [39 60 38  6]
 [59  5 41 56]
 [78 61 82 73]
 [32 38 78 35]
 [40 88 13 20]
 [48 52 50 42]] 

1-2.과목 점수별 ABCD 입니다. (10 X 4).
 [['D' 'D' 'D' 'D']
 ['D' 'C' 'D' 'D']
 ['D' 'A' 'D' 'D']
 ['D' 'D' 'A' 'A']
 ['C' 'B' 'D' 'D']
 ['D' 'D' 'D' 'D']
 ['D' 'D' 'D' 'D']
 ['C' 'D' 'B' 'C']
 ['D' 'D' 'C' 'D']
 ['D' 'B' 'D' 'D']] 

1-3. 점수-평균의 값입니다. (10 X 4)
 [[ 17 -41   8  -6]
 [-18  21 -40  10]
 [  8  43 -24 -15]
 [-35 -52  48  57]
 [ 28  37  10 -25]
 [ -9   8 -12 -36]
 [ 11 -47  -9  14]
 [ 30   9  32  31]
 [-16 -14  28  -7]
 [ -8  36 -37 -22]] 

1-4. 학생별 과목총합과 평균의 총합을 추가한 배열입니다. (11 X 5)
 [[ 65  11  58  36 170]
 [ 30  73  10  52 165]
 [ 56  95  26  27 204]
 [ 13   0  98  99 210]
 [ 76  89  60  17 242]
 [ 