In [3]:
import numpy as np

def main():
    print("정보통신공학과 60191896 김수정\n")
    
    #점수 배열
    Score = np.random.randint(100, size=(10, 4))
    print("10명 학생의 국영수과 점수 리스트입니다.\n", Score, "\n")
    math_score(Score)
    total_score(Score)
    odd_student(Score)
    change_array(Score)


#1-1. 모든 학생의 수학 점수 출력
def math_score(ScoreList):
    print("1-1.모든 학생의 수학 점수입니다.")
    print(ScoreList[:, 2:3], "\n")


#1-2. 각 학생의 총 합 점수 출력
def total_score(ScoreList):
    total = 0
    change_row = 0 #열을 바꾸기 위한 변수
    print("1-2.각 학생 과목의 총 합 점수입니다.")
    
    for i in range(10):
        for j in range(4):
            total += ScoreList[i][j]
        print(i+1, "번째 학생의 총 합 점수는", total, "입니다.")

        #change_row값을 before에 대입, 같지 않을 시 total값 초기화
        before_value = change_row
        change_row += 1
        if (before_value != change_row):
            total = 0
    print("\n")


#1-3. 불린인덱스로 홀수번째 학생의 과목만 출력
def odd_student(ScoreList):
    cond = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

    for i in range(10):
        #cond배열요소 값이 홀수일때,
        if (cond[i] % 2 == 1):
            cond[i] = True
        #cond배열요소 값이 짝수일때,
        else:
            cond[i] = False
            
    print("1-3.홀수번째 학생들의 과목점수입니다.\n", ScoreList[cond == True])
    print("\n")


#1-4. 행열 변환하여 출력
def change_array(ScoreList):
    Score = ScoreList.transpose((1, 0))
    print("1-4.행렬변환\n", Score)


main()

정보통신공학과 60191896 김수정

10명 학생의 국영수과 점수 리스트입니다.
 [[59 44  0 10]
 [93 61 70 80]
 [11 68 76 29]
 [29 53 43 16]
 [62  2 75 34]
 [95 14 78 46]
 [82  3 50 94]
 [ 2 58 67 69]
 [ 1 49 47 77]
 [12  2 24 74]] 

1-1.모든 학생의 수학 점수입니다.
[[ 0]
 [70]
 [76]
 [43]
 [75]
 [78]
 [50]
 [67]
 [47]
 [24]] 

1-2.각 학생 과목의 총 합 점수입니다.
1 번째 학생의 총 합 점수는 113 입니다.
2 번째 학생의 총 합 점수는 304 입니다.
3 번째 학생의 총 합 점수는 184 입니다.
4 번째 학생의 총 합 점수는 141 입니다.
5 번째 학생의 총 합 점수는 173 입니다.
6 번째 학생의 총 합 점수는 233 입니다.
7 번째 학생의 총 합 점수는 229 입니다.
8 번째 학생의 총 합 점수는 196 입니다.
9 번째 학생의 총 합 점수는 174 입니다.
10 번째 학생의 총 합 점수는 112 입니다.


1-3.홀수번째 학생들의 과목점수입니다.
 [[59 44  0 10]
 [11 68 76 29]
 [62  2 75 34]
 [82  3 50 94]
 [ 1 49 47 77]]


1-4.행렬변환
 [[59 93 11 29 62 95 82  2  1 12]
 [44 61 68 53  2 14  3 58 49  2]
 [ 0 70 76 43 75 78 50 67 47 24]
 [10 80 29 16 34 46 94 69 77 74]]
